image:
  file: Dockerfile
ports:
  - port: 8080
  - port: 3306
    onOpen: ignore
tasks:
  - name: MySQL
    command: >
        mysqld --initialize-insecure;
        mysqld
  - name: Apache
    command: >
        apachectl start;
