image:
  file: Dockerfile
ports:
 - port: 8080
   onOpen: open-preview
tasks:
 - name: Apache
   command: >
    apachectl start;
 - name: Lamp
   command: >
     chmod 777 $GITPOD_REPO_ROOT/.htaccess;
     cd $GITPOD_REPO_ROOT;