image:
  file: Dockerfile
ports:
 - port: 8080
   onOpen: open-preview
tasks:
 - name: MySQL
   command: >
    mysqld
 - name: Apache
   command: >
    apachectl start;
 - init: mysqladmin -u root password cit2318